### ISSUE TITLE
Name collision.

### ISSUE THREAD

**Issue by MelonCode** [Thinkofname/stylish#16]
Hello. Just wanted to make you know that there is a popular browser extension with same name (Currently 1.6M downloads).
That's not issue, but maybe you decide to rename project while it is on begining stage.

**Comment by Thinkofname** [comment]
Whilst I don't think the name conflict is a major issue (different things: theming vs a ui manager) I am up for a name change. The issue is i'm pretty terrible at naming things so i'm up for suggestions.

**Comment by Thinkofname** [comment]
Renamed to fungui
