### ISSUE TITLE
Fix/Rewrite parsers

### ISSUE THREAD

**Issue by Thinkofname** [Thinkofname/stylish#2]
The current ones don't handle errors very well

**Comment by Thinkofname** [comment]
https://github.com/Thinkofname/stylish/commit/c31f02fb0a9285888554a1007c270bf6b318c20c Fixes my major issue with the style parser

**Comment by ghost** [comment]
Would you like me to write an html macro parser? I've done it before on an older version of rust but didn't have a use for it.

```
dom!(<a href={link} onclick={this.handleClick()}>{text}</a>)
```

**Comment by Thinkofname** [comment]
Something like that but for the stylish-syntax already exists here: https://github.com/Thinkofname/stylish/blob/master/src/macros.rs#L39

This issue is targeting the runtime parsers here: https://github.com/Thinkofname/stylish/tree/master/syntax/src
