### ISSUE TITLE
Name clashes (?) in style functions

### ISSUE THREAD

**Issue by EdorianDark** [Thinkofname/stylish#20]
In style/mod.rs
> root > panel > image(width=width, height=height) {
>     width = width,
>     height = height,
> }

It looks like `width` refers to several meanings.

**Comment by Thinkofname** [comment]
Its not the clearest thing
```
root > panel > image(width=width, height=height) {
                     ^^^^^ - Property key
                           ^^^^^ - Variable binding
    width = width,
    ^^^^^ - Style key
            ^^^^^ - Variable usage
    height = height,
}
```

Originally I had variables prefixed with `$` to make this slightly clearer but I found out some keyboard don't have this in an easy to type place. I'm open to suggestions on how to improve this though

**Comment by EdorianDark** [comment]
I would suggest something like the following
```
root > panel > image(width, height) {
    self.width = width,
    self.height = height,
}
```

**Comment by Thinkofname** [comment]
The issue I have with that is that there isn't ever a time where it wouldn't be `self.` making it somewhat pointless noise for every line.

Edit: That being said maybe having a `.` prefix wouldn't be too bad? Still noise but less of it

**Comment by Thinkofname** [comment]
Just a note: The names don't have to clash, its just a poor example

```
window > content(style="build_room") > scroll_panel(rows=num_rows) > content {
    layout = "grid",
    columns = 3,
    rows = num_rows,
    spacing = 2,
    margin = 2,
    height = num_rows * 170,
    scroll_height = num_rows * 170,
}
```
From my own project.

**Comment by EdorianDark** [comment]
So the "Style key" refers to a property defined somewhere else and the "Variable usage/usage" to the new value of the property.
Can you explain why you need a "Property key"? 

You are right, a `.self`  would be too noisy.

**Comment by Thinkofname** [comment]
Style keys are used by the render (e.g. webrender). See the `get_*value` calls in here https://github.com/Thinkofname/stylish/blob/master/webrender/src/lib.rs#L336-L345.

Property keys are basically like matching on attributes on html elements.

e.g.

Style rules:
```
// 1
example(color=col) {
    background_color = col,
}
// 2
example(focused=true) {
    background_color = "#ff0000",
}
// 3
example(size=size) {
    width = size,
    height = size,
}
```

Then the following nodes would have the style rules tested and applied as followed

```
// Has 1 effecting it
example(col="#00ffff")
// Has 1 and 3 effecting it
example(col="#00ff00", size=10)
// Has 2 and 3 effecting it
example(focused=true, size=16)
// Has 1 and  2 effecting it but since background_color is in both
// only the 2's background applies
example(col="#0000ff", focused=true)
```
