### ISSUE TITLE
demo.rs, grey grid box borders looks weird on macOS

### ISSUE THREAD

**Issue by anderejd** [Thinkofname/stylish#24]
<img width="912" alt="screen shot 2017-11-18 at 11 15 21" src="https://user-images.githubusercontent.com/3704611/32979246-ceb204fa-cc51-11e7-9dea-a81b95cd7599.png">

Looks different from the demo screenshot in the readme. Is the screenshot in the readme showing the expected result?

**Comment by Thinkofname** [comment]
Yeah the readme is. I guess something broke at some point when i've updated webrender

**Comment by Thinkofname** [comment]
I've removed the rendering side of this crate now (It only handles layout now).
