### ISSUE TITLE
Window resize on macOS

### ISSUE THREAD

**Issue by anderejd** [Thinkofname/stylish#25]
Flickering and scaling issues when resizing the window on macOS:
<img width="977" alt="screen shot 2017-11-18 at 11 18 04" src="https://user-images.githubusercontent.com/3704611/32979276-7561b19c-cc52-11e7-87d7-710e4a0c235b.png">

**Comment by anderejd** [comment]
I'm taking a look at this.

**Comment by anderejd** [comment]
I did the rustfmt PR first. Awaiting the verdict on that PR before resuming this.

EDIT: That PR was just merged. But I'm putting away the code for today, maybe I'll pick this up tomorrow. I suspect I will look at this one hour here and there for the next week or so.

**Comment by anderejd** [comment]
Could not let go of the laptop, fixed the visual bugs: https://github.com/Thinkofname/stylish/pull/28

EDIT: I changed my mind and closed the PR, it was a bit too hastily slapped together. See comment in the PR.

**Comment by 171230839** [comment]
Change the  events_loop.poll_events function to events_loop.run_forever function in demo.rs 393 line, and take The change of the corresponding。

**Comment by stalkerg** [comment]
I have no Hidpi on macos and I have the same problem.

**Comment by Thinkofname** [comment]
I've removed the rendering side of this crate now (It only handles layout now).
