### ISSUE TITLE
rustfmt?

### ISSUE THREAD

**Issue by anderejd** [Thinkofname/stylish#26]
Would using rustfmt be acceptable to this project?

How to use the latest rustfmt using default formatting with stable rust as the default toolchain:

```
cargo +nightly install rustfmt-nightly -f
cargo +nightly fmt
```

The nightly rust toolchain needs to be installed but does not need to be default and the project being formatted can use the normal stable toolchain, only the formatting tool needs to use nightly.

**Comment by Thinkofname** [comment]
Haven't always been a fan of rustfmt's output but a quick run of it now seems to be acceptable. Might be worth doing after the open PR is merged
