### ISSUE TITLE
Crates.io

### ISSUE THREAD

**Issue by Thinkofname** [Thinkofname/stylish#9]
I don't think this is possible because webrender isn't on crates.io but its worth looking into

**Comment by anderejd** [comment]
You could vendor webrender inside stylish.

EDIT: Maybe git subtree could be useful but I have never tried that and I absolutely loathe git submodules so I can't recommend that either. Stylish can probably wait for webrender to get published to crates.io first?

**Comment by Thinkofname** [comment]
Done as webrender isn't included anymore
